coverage:
  status:
    project:
      default:
        target: auto
      javac:
        target: 75%
        flags:
          - javac
      response:
        target: 90%
        flags:
          - response
      schema:
        target: 80%
        flags:
          - schema

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: yes
  require_head: yes
  branches: null

flags:
  javac:
    paths:
      - javac
    carryforward: true
  response:
    paths:
      - response
    carryforward: true
  schema:
    paths:
      - schema
    carryforward: true
