name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
      CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup openjdk
        uses: actions/setup-java@v1
        with:
          java-version: 16

      - name: Setup clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest

      - name: Cache deps
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Cleanup
        run: make clean

      - name: Run tests
        run: make test

      - name: Upload coverage
        run: make coverage

      - name: Update pom.xml
        run: make pom

      - name: Build jar
        run: make jar

      - name: Deploy jar
        run: make deploy
